### ISSUE TITLE
⛰️[EPIC]: Model Parallel SFNO Integration

### ISSUE THREAD

**Issue by NickGeneva** [NVIDIA/physicsnemo#113]
Tracking model parallel SFNO integration into Modulus core / launch
```[tasklist]
### Core
- [ ] https://github.com/NVIDIA/modulus/issues/58
- [ ] https://github.com/NVIDIA/modulus/issues/79
- [ ] https://github.com/NVIDIA/modulus/issues/75
- [ ] https://github.com/NVIDIA/modulus/issues/133
- [ ] https://github.com/NVIDIA/modulus/issues/142
- [ ] https://github.com/NVIDIA/modulus/issues/154
```

```[tasklist]
### Launch
- [ ] https://github.com/NVIDIA/modulus-launch/issues/48
- [ ] https://github.com/NVIDIA/modulus-launch/issues/49
```
